// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEnnbWcPQUtnjeVX5Oleg2LjKHtSRwHI',
    appId: '1:162459881850:web:1972d7393da68522b2c6c3',
    messagingSenderId: '162459881850',
    projectId: 'notes-3d9e3',
    authDomain: 'notes-3d9e3.firebaseapp.com',
    storageBucket: 'notes-3d9e3.firebasestorage.app',
    measurementId: 'G-65HCH90N1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVy2pKJ8WX-uSaC6zyeAubi92zWYVeDo',
    appId: '1:162459881850:android:1209fbbb22d6ef03b2c6c3',
    messagingSenderId: '162459881850',
    projectId: 'notes-3d9e3',
    storageBucket: 'notes-3d9e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvsWmcL4abrQugj4CJFQo4yHQ65I8ZN4',
    appId: '1:162459881850:ios:d9308019f29acf37b2c6c3',
    messagingSenderId: '162459881850',
    projectId: 'notes-3d9e3',
    storageBucket: 'notes-3d9e3.firebasestorage.app',
    iosBundleId: 'com.example.task10',
  );
}
